blueprint:
  name: smart plug control based on solar input
  description: Turn a smart plug on/off based on solar input.
  domain: automation
  input:
    pv_power_sensor:
      name: PV Power Total
      description: This sensor will be synchronized with the smart plug.
      selector:
        entity:
          filter:
            - domain: sensor
    target_light:
      name: Smart Plug
      description: The smart plug to keep in sync.
      selector:
        entity:
          filter:
            - domain: light
    battery_capacity_sensor:
      name: Battery Capacity
      description: This sensor will be synchronized with the smart plug.
      selector:
        entity:
          filter:
            - domain: sensor
    above_power:
      name: above-value
      description: This input value defines the above-value of solar input.
    under_power:
      name: under-value
      description: This input value defines the under-value of solar input.
    battery_capacity:
      name: Battery Capacity
      description: This input value defines the battery capacity.

triggers:
  - trigger: numeric_state
    entity_id: !input pv_power_sensor
  - trigger: numeric_state
    entity_id: !input battery_capacity_sensor
  
alias: Elektrische Heizung 1 turn on/off
triggers:
  - alias: more then 2600 Watt input into power grid
    trigger: numeric_state
    entity_id: !input pv_power_sensor
    id: above-2600
    above: 2600 
  - alias: less then 2300 Watt input into power grid
    trigger: numeric_state
    entity_id: !input pv_power_sensor
    below: 2300  
    id: under-2300
conditions:
  - condition: numeric_state
    entity_id: !input battery_capacity_sensor
    above: 70  
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - above-2600  
        sequence:
          - action: light.turn_on
            target: !input target_light
      - conditions:
          - condition: trigger
            id:
              - under-2300  
        sequence:
          - action: light.turn_off
            target: !input target_light
mode: single
