blueprint:
  name: Tuya TS0044 – 4 Button Switch (ZHA / remote_button)
  description: >
    Blueprint für Tuya TS0044 4-Button Switch über ZHA.
    Unterstützt short, double und long press.
  domain: automation

  input:
    mode:
      name: Automation Mode
      default: parallel
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel

    zigbee_device:
      name: ZHA Device – Tuya TS0044
      selector:
        device:
          integration: zha

    # Button 1
    button_1_short:
      name: Button 1 – Short Press
      default: []
      selector: { action: {} }
    button_1_double:
      name: Button 1 – Double Press
      default: []
      selector: { action: {} }
    button_1_long:
      name: Button 1 – Long Press
      default: []
      selector: { action: {} }

    # Button 2
    button_2_short:
      name: Button 2 – Short Press
      default: []
      selector: { action: {} }
    button_2_double:
      name: Button 2 – Double Press
      default: []
      selector: { action: {} }
    button_2_long:
      name: Button 2 – Long Press
      default: []
      selector: { action: {} }

    # Button 3
    button_3_short:
      name: Button 3 – Short Press
      default: []
      selector: { action: {} }
    button_3_double:
      name: Button 3 – Double Press
      default: []
      selector: { action: {} }
    button_3_long:
      name: Button 3 – Long Press
      default: []
      selector: { action: {} }

    # Button 4
    button_4_short:
      name: Button 4 – Short Press
      default: []
      selector: { action: {} }
    button_4_double:
      name: Button 4 – Double Press
      default: []
      selector: { action: {} }
    button_4_long:
      name: Button 4 – Long Press
      default: []
      selector: { action: {} }

mode: !input mode
max_exceeded: silent

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zigbee_device

action:
  - variables:
      endpoint: "{{ trigger.event.data.endpoint_id }}"
      command: "{{ trigger.event.data.command }}"

  - choose:
      # Button 1
      - conditions: "{{ endpoint == 1 and command == 'remote_button_short_press' }}"
        sequence: !input button_1_short
      - conditions: "{{ endpoint == 1 and command == 'remote_button_double_press' }}"
        sequence: !input button_1_double
      - conditions: "{{ endpoint == 1 and command == 'remote_button_long_press' }}"
        sequence: !input button_1_long

      # Button 2
      - conditions: "{{ endpoint == 2 and command == 'remote_button_short_press' }}"
        sequence: !input button_2_short
      - conditions: "{{ endpoint == 2 and command == 'remote_button_double_press' }}"
        sequence: !input button_2_double
      - conditions: "{{ endpoint == 2 and command == 'remote_button_long_press' }}"
        sequence: !input button_2_long

      # Button 3
      - conditions: "{{ endpoint == 3 and command == 'remote_button_short_press' }}"
        sequence: !input button_3_short
      - conditions: "{{ endpoint == 3 and command == 'remote_button_double_press' }}"
        sequence: !input button_3_double
      - conditions: "{{ endpoint == 3 and command == 'remote_button_long_press' }}"
        sequence: !input button_3_long

      # Button 4
      - conditions: "{{ endpoint == 4 and command == 'remote_button_short_press' }}"
        sequence: !input button_4_short
      - conditions: "{{ endpoint == 4 and command == 'remote_button_double_press' }}"
        sequence: !input button_4_double
      - conditions: "{{ endpoint == 4 and command == 'remote_button_long_press' }}"
        sequence: !input button_4_long
